### ISSUE TITLE
Editions page crashing

### ISSUE THREAD

**Issue by EnsignEvident** [jenwalter666/JensBalatroCollection#6]
My game crashes every time a certain edition of card tries to load. This happens both trying to view the edition in the collections tab or receiving any card/joker with it via any means. included is the crash log from an attempt to view editions via the collections tab.
[Oops! The game crashed.txt](https://github.com/user-attachments/files/16823107/Oops.The.game.crashed.txt)

**Comment by FearChub** [comment]
Hey what was the fix to this?
